Немного о метриках:
Flesch Reading Ease - Рассчитывается через среднюю длину предложений и среднее число слогов на слово. Оценивает читаемость текста по шкале от 0 до 100 (может быть больше 100 и меньше 0): чем выше, тем текст легче.

SMOG - то же самое, что и Gunning Fog (различие: Gunning Fog - берется средняя длина предложения и сложные слова в предложении, SMOG - квадратный корень сложных слов на предложение) 

Coleman-Liau Index - Учитывает количество букв вместо слогов – упрощает автоматический расчет (среднее число букв на 100 слов и среднее число предложений на 100 слов). Результат – примерный класс образования: чем выше, тем сложнее

In [30]:
from pathlib import Path
import pandas as pd
from ruts import ReadabilityStats
import textstat

In [31]:
# тексты
folder_path = Path('/Users/sergey/Library/Mobile Documents/com~apple~CloudDocs/Учеба СПбГУ/Семантические анализаторы/Экзамен/Оценка сложности текстов/10 Texts')

# Считываем все файлы в словарь
texts = {}
for filepath in folder_path.glob("*.txt"):
    with open(filepath, encoding="utf-8") as f:
        texts[filepath.name] = f.read()

RUTS

In [32]:
rows = []

for filename, text in texts.items():
    rs = ReadabilityStats(text)
    stats = rs.get_stats()
    stats["Файл"] = filename
    rows.append(stats)

# Создание DataFrame и перестановка колонок
df_ruts = pd.DataFrame(rows)
df_ruts = df_ruts[["Файл", 
                   "flesch_kincaid_grade",
                   "flesch_reading_easy",
                   "coleman_liau_index",
                   "smog_index",
                   "automated_readability_index",
                   "lix"]]

df_ruts

,Файл,flesch_kincaid_grade,flesch_reading_easy,coleman_liau_index,smog_index,automated_readability_index,lix
0,Mikoni_IMS_2020_rus.txt,11.342874,17.391127,13.170859,20.032338,13.935257,76.317144
1,Grebennikov_IMS_2020_rus.txt,15.116181,13.334427,13.282493,24.193219,15.758286,82.652574
2,Brodovskaya_Siniakov_IMS_2014_rus.txt,15.123434,3.058477,16.372443,24.941937,18.514572,83.674293
3,Bakhvalov_IMS_2020_rus.txt,10.643372,29.709257,10.862231,18.638911,11.606118,76.611959
4,Korablinov_IMS_2020_rus.txt,10.747330,26.619409,12.099673,18.716838,12.900590,78.100273
5,Chugunov_IMS_2014_rus.txt,13.339662,11.368561,14.597966,23.689339,16.078644,81.202200
6,Khokhlova_IMS_2020_rus.txt,14.186355,10.729468,14.836248,24.333190,16.763057,83.761439
7,Kuznetsova_IMS_2020_rus.txt,13.658817,19.970737,12.249272,23.831995,14.171290,82.122607
8,Sokolova_IMS_2020_rus.txt,10.975274,32.752950,10.059134,21.268198,11.031861,77.112002
9,Rogov_IMS_2020_rus.txt,16.532444,11.243889,13.139976,25.937124,16.377656,87.207092

textstat

In [33]:
textstat_results = []

for filename, text in texts.items():
    textstat_results.append({
        "Файл": filename,
        "Flesch Reading Ease": textstat.flesch_reading_ease(text),
        "SMOG Index": textstat.smog_index(text),
        "Flesch-Kincaid Grade": textstat.flesch_kincaid_grade(text),
        "Coleman-Liau Index": textstat.coleman_liau_index(text),
        "Automated Readability Index": textstat.automated_readability_index(text),
        "Dale-Chall Score": textstat.dale_chall_readability_score(text)
    })

df_textstat = pd.DataFrame(textstat_results)
df_textstat

,Файл,Flesch Reading Ease,SMOG Index,Flesch-Kincaid Grade,Coleman-Liau Index,Automated Readability Index,Dale-Chall Score
0,Mikoni_IMS_2020_rus.txt,107.524891,3.908917,1.742841,21.690071,18.442089,19.932540
1,Grebennikov_IMS_2020_rus.txt,102.177337,3.129100,3.904812,20.474519,20.134325,20.404247
2,Brodovskaya_Siniakov_IMS_2014_rus.txt,100.617750,3.767804,4.479422,24.507683,23.467269,20.466208
3,Bakhvalov_IMS_2020_rus.txt,104.265320,4.739549,2.788323,18.750141,17.043128,20.137403
4,Korablinov_IMS_2020_rus.txt,102.936639,5.496819,3.010701,20.639614,18.576491,20.223451
5,Chugunov_IMS_2014_rus.txt,100.783522,5.042226,4.012729,23.430985,22.171406,20.348875
6,Khokhlova_IMS_2020_rus.txt,99.492265,5.341637,4.222358,24.094440,22.875515,20.244293
7,Kuznetsova_IMS_2020_rus.txt,95.073271,6.602605,5.299816,22.086850,21.912083,19.910915
8,Sokolova_IMS_2020_rus.txt,98.269458,6.659672,3.736306,20.303753,18.944407,20.098994
9,Rogov_IMS_2020_rus.txt,99.373412,3.129100,4.984353,20.473936,21.428283,20.541700

In [36]:
#для русского языка работает только одна метрика
import textstat
textstat.set_lang("ru")

rows = []

for filename, text in texts.items():
    rows.append({
        "Файл": filename,
        "Flesch Reading Ease (ru)": textstat.flesch_reading_ease(text)
    })

df_textstat_ru = pd.DataFrame(rows)
df_textstat_ru

                                    Файл  Flesch Reading Ease (ru)
0                Mikoni_IMS_2020_rus.txt                 25.554977
1           Grebennikov_IMS_2020_rus.txt                 24.002382
2  Brodovskaya_Siniakov_IMS_2014_rus.txt                  8.843546
3             Bakhvalov_IMS_2020_rus.txt                 36.527619
4            Korablinov_IMS_2020_rus.txt                 30.914502
5              Chugunov_IMS_2014_rus.txt                 14.732838
6             Khokhlova_IMS_2020_rus.txt                 15.601876
7            Kuznetsova_IMS_2020_rus.txt                 23.304893
8              Sokolova_IMS_2020_rus.txt                 36.563794
9                 Rogov_IMS_2020_rus.txt                 21.938058