Импортируем библиотеки

In [1]:
import nltk
import random
import numpy as np
import pandas as pd
import pprint, time
from sklearn.model_selection import train_test_split

In [15]:
from tqdm import notebook

Скачиваем данные из Github

In [19]:
!wget https://raw.githubusercontent.com/appling2024/data/refs/heads/main/GSD_train.txt
!wget https://raw.githubusercontent.com/appling2024/data/refs/heads/main/GSD_test.txt

--2024-11-07 21:28:34--  https://raw.githubusercontent.com/appling2024/data/refs/heads/main/GSD_train.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7626752 (7.3M) [text/plain]
Saving to: ‘GSD_train.txt.1’

GSD_train.txt.1     100%[===================>]   7.27M   623KB/s    in 13s

2024-11-07 21:28:47 (584 KB/s) - ‘GSD_train.txt.1’ saved [7626752/7626752]

--2024-11-07 21:28:48--  https://raw.githubusercontent.com/appling2024/data/refs/heads/main/GSD_test.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 81386 (79K) [text/plain]
Saving to: ‘GSD_test.txt.1’

GSD_test.txt.1      100%[===================>]  79.48K  --.-KB/s    in 0.06s

2024-11-07 21:28:48 (1.29 MB/s) - ‘GSD_test.txt.1’ saved [81386/81386]

In [2]:
with open("GSD_train.txt", encoding='utf-8') as f:
  data = f.read()

In [3]:
sent = data.split('\n\n')

Представляем данные в виде списка, который содержит другие списки

In [4]:
tokens = []
for sentence in sent:
    s = []
    for word in sentence.split('\n'):
        if word:
            token = (word.split()[1], word.split()[3])
        s.append(token)
    tokens.append(s)

Подготовка к обучению HMM

In [5]:
train_set,test_set =train_test_split(tokens, train_size=0.80, test_size=0.20, random_state = 101)

Создаем список размеченных обучающих и тестовых данных

In [6]:
train_tagged_words = [ tup for sent in train_set for tup in sent ]
test_tagged_words = [ tup for sent in test_set for tup in sent ]

Рассчитываем вероятности эмиссии
они определяют вероятность увидеть определенную наблюдаемую переменную при заданном значении для скрытых переменных,
т.е. эта функция возвращает то, сколько всего раз тег встречался в выборке и сколько раз определенное слово встречалось с этим тегом

In [7]:
def word_given_tag(word, tag, train_bag=train_tagged_words):
    tag_list = [pair for pair in train_bag if pair[1]==tag] # список всех слов определенного тега
    count_tag = len(tag_list)# общее число появления тегов в обучающей выборке
    w_given_tag_list = [pair[0] for pair in tag_list if pair[0]==word] # cписок, который состоит из всех вхождений данного слова, которые были помечены определенным тегом
    count_w_given_tag = len(w_given_tag_list) # подсчитываем общее количество раз, когда слово встречалось с тегом

    return (count_w_given_tag, count_tag)

Рассчитываем вероятность переходов

In [8]:
def t2_given_t1(t2, t1, train_bag=train_tagged_words): # t1 = t2, это пронумерованный список тегов
    tags = [pair[1] for pair in train_bag] # список всех тегов по порядку (просто из общего спсика размеченных слов мы убираем слова, получаем последовательность тегов)
    count_t1 = len([t for t in tags if t==t1])
    count_t2_t1 = 0
    for index in range(len(tags)-1):
        if tags[index]==t1 and tags[index+1] == t2: # если при теге t1 следующий тег = t2, то осуществляется переход
            count_t2_t1 += 1
    return (count_t2_t1, count_t1) # сколько всего раз встречается данный (второе значение), сколько раз данный тег переходит в другой тег (первое значение)

создаем матрицу тегов t x t, где t - номер тега
матрица(i, j) представляет вероятность перехода P(i-й тег переходит в j-й тег)

In [9]:
tags = list(set([pair[1] for pair in train_tagged_words]))
tags_matrix = np.zeros((len(tags), len(tags)), dtype='float32')
for i, t1 in enumerate(list(tags)):
    for j, t2 in enumerate(list(tags)):
        tags_matrix[i, j] = t2_given_t1(t2, t1)[0]/t2_given_t1(t2, t1)[1]

print(tags_matrix)

[[8.16326495e-03 1.06122447e-02 1.63265306e-03 7.14285731e-01
  3.26530612e-03 0.00000000e+00 1.26530617e-01 4.89795916e-02
  1.95918363e-02 1.63265299e-02 9.79591813e-03 3.26530612e-03
  5.71428565e-03 2.44897953e-03 2.44897953e-03 2.69387756e-02]
 [4.20673098e-03 1.38221150e-02 3.00480775e-03 5.49879789e-01
  1.20192312e-03 4.20673080e-02 9.37500000e-02 3.00480775e-03
  1.50240380e-02 1.79086536e-01 4.20673098e-03 0.00000000e+00
  6.00961561e-04 6.00961549e-03 1.68269239e-02 6.73076957e-02]
 [6.31911540e-03 1.10584516e-02 4.73933667e-03 8.21484998e-02
  6.16113730e-02 0.00000000e+00 1.10584520e-01 2.21169032e-02
  6.60347581e-01 7.89889414e-03 6.31911540e-03 0.00000000e+00
  3.15955770e-03 1.57977885e-03 4.73933667e-03 1.73775665e-02]
 [1.01723652e-02 1.29038338e-02 1.19619481e-02 1.51549399e-01
  1.23857968e-02 1.31863996e-03 1.11330882e-01 6.64029410e-03
  8.39691088e-02 3.34039748e-01 7.56805092e-02 1.88377133e-04
  7.67636811e-03 9.32466798e-03 4.21964787e-02 1.28661588e-01]
 [1.34983128e-02 3.26209217e-02 1.34983128e-02 6.18672669e-02
  4.89313826e-02 5.62429719e-04 1.28233969e-01 4.89313826e-02
  2.88526446e-01 1.16985373e-01 1.34983128e-02 6.18672650e-03
  3.65579315e-02 3.37457820e-03 2.13723276e-02 1.65354326e-01]
 [6.94444450e-03 1.31944448e-01 0.00000000e+00 2.63888896e-01
  0.00000000e+00 4.16666679e-02 7.63888881e-02 0.00000000e+00
  9.02777761e-02 1.80555552e-01 2.08333340e-02 0.00000000e+00
  6.94444450e-03 9.02777761e-02 6.94444450e-03 8.33333358e-02]
 [2.16517178e-03 1.95896486e-03 2.98999902e-03 7.36364603e-01
  2.68068863e-03 2.06206823e-04 8.56789351e-02 2.26827501e-03
  1.26817198e-02 8.56789351e-02 1.93834417e-02 1.03103412e-04
  1.54655124e-03 9.27930698e-04 2.19610278e-02 2.34044753e-02]
 [1.99063234e-02 3.04449648e-02 2.69320849e-02 1.35831386e-01
  6.44028112e-02 0.00000000e+00 1.06557377e-01 3.39578465e-02
  3.85245889e-01 3.16159241e-02 4.44964878e-02 3.51288053e-03
  1.05386414e-02 0.00000000e+00 0.00000000e+00 1.06557377e-01]
 [2.80597024e-02 3.83582078e-02 3.73134320e-03 2.34179109e-01
  3.55223864e-02 4.47761180e-04 1.49552241e-01 1.68656725e-02
  4.94029857e-02 7.92537332e-02 2.47761197e-02 5.97014907e-04
  2.64179111e-02 2.68656714e-03 9.99999978e-03 3.00149262e-01]
 [1.34491455e-02 2.93499585e-02 5.18352492e-03 1.65802747e-01
  4.73521985e-02 1.12076208e-03 1.24264501e-01 9.45643056e-03
  9.91874486e-02 1.18310452e-01 9.44242105e-02 2.71084346e-02
  3.46035287e-02 2.71784812e-02 5.16251065e-02 1.51513025e-01]
 [1.90621428e-03 4.57491400e-03 1.75371710e-02 1.52497143e-02
  1.33435000e-02 7.62485724e-04 3.16431560e-02 9.72169265e-03
  1.12085402e-01 4.97903168e-01 1.62218839e-01 0.00000000e+00
  2.09683576e-03 2.09683576e-03 5.66145629e-02 7.22455233e-02]
 [3.56347449e-02 1.33630289e-02 6.68151444e-03 2.04899773e-01
  6.68151453e-02 0.00000000e+00 1.02449887e-01 5.34521155e-02
  1.60356343e-01 2.44988855e-02 5.79064600e-02 2.67260578e-02
  9.79955420e-02 4.45434311e-03 1.11358576e-02 1.33630291e-01]
 [7.83289783e-03 1.50130549e-02 4.76501323e-02 7.70234987e-02
  5.61357699e-02 0.00000000e+00 5.61357699e-02 5.67885116e-02
  4.25587475e-01 1.35770231e-01 1.30548300e-02 5.22193220e-03
  2.34986953e-02 1.30548305e-03 7.83289783e-03 7.11488277e-02]
 [8.05152988e-04 3.05958129e-02 7.24637695e-03 6.44122390e-03
  3.22061195e-03 6.44122390e-03 8.05152953e-03 6.44122390e-03
  3.70370373e-02 4.32367146e-01 5.63607085e-03 0.00000000e+00
  0.00000000e+00 4.06602263e-01 2.81803533e-02 2.09339783e-02]
 [2.45526433e-02 2.62172278e-02 7.07449019e-03 2.57178515e-01
  6.15896806e-02 1.24843942e-03 1.77694544e-01 2.70495210e-02
  1.31086141e-01 3.37078646e-02 8.57261792e-02 5.82605088e-03
  1.99750308e-02 1.12359552e-02 2.78818142e-02 1.01955891e-01]
 [5.25202677e-02 4.64105271e-02 0.00000000e+00 4.59992945e-01
  5.87475020e-03 3.52485018e-04 2.68123597e-01 1.52743503e-03
  6.10974012e-03 1.16320057e-02 8.68288130e-02 1.17495008e-04
  5.39302081e-02 5.75725548e-03 1.17495008e-04 7.04970036e-04]]

In [10]:
tags_df = pd.DataFrame(tags_matrix, columns = list(tags), index=list(tags))
display(tags_df)

,DET,NUM,AUX,NOUN,ADV,SYM,ADJ,PART,VERB,PUNCT,PROPN,SCONJ,PRON,X,CCONJ,ADP
DET,0.008163,0.010612,0.001633,0.714286,0.003265,0.000000,0.126531,0.048980,0.019592,0.016327,0.009796,0.003265,0.005714,0.002449,0.002449,0.026939
NUM,0.004207,0.013822,0.003005,0.549880,0.001202,0.042067,0.093750,0.003005,0.015024,0.179087,0.004207,0.000000,0.000601,0.006010,0.016827,0.067308
AUX,0.006319,0.011058,0.004739,0.082148,0.061611,0.000000,0.110585,0.022117,0.660348,0.007899,0.006319,0.000000,0.003160,0.001580,0.004739,0.017378
NOUN,0.010172,0.012904,0.011962,0.151549,0.012386,0.001319,0.111331,0.006640,0.083969,0.334040,0.075681,0.000188,0.007676,0.009325,0.042196,0.128662
ADV,0.013498,0.032621,0.013498,0.061867,0.048931,0.000562,0.128234,0.048931,0.288526,0.116985,0.013498,0.006187,0.036558,0.003375,0.021372,0.165354
SYM,0.006944,0.131944,0.000000,0.263889,0.000000,0.041667,0.076389,0.000000,0.090278,0.180556,0.020833,0.000000,0.006944,0.090278,0.006944,0.083333
ADJ,0.002165,0.001959,0.002990,0.736365,0.002681,0.000206,0.085679,0.002268,0.012682,0.085679,0.019383,0.000103,0.001547,0.000928,0.021961,0.023404
PART,0.019906,0.030445,0.026932,0.135831,0.064403,0.000000,0.106557,0.033958,0.385246,0.031616,0.044496,0.003513,0.010539,0.000000,0.000000,0.106557
VERB,0.028060,0.038358,0.003731,0.234179,0.035522,0.000448,0.149552,0.016866,0.049403,0.079254,0.024776,0.000597,0.026418,0.002687,0.010000,0.300149
PUNCT,0.013449,0.029350,0.005184,0.165803,0.047352,0.001121,0.124265,0.009456,0.099187,0.118310,0.094424,0.027108,0.034604,0.027178,0.051625,0.151513
PROPN,0.001906,0.004575,0.017537,0.015250,0.013343,0.000762,0.031643,0.009722,0.112085,0.497903,0.162219,0.000000,0.002097,0.002097,0.056615,0.072246
SCONJ,0.035635,0.013363,0.006682,0.204900,0.066815,0.000000,0.102450,0.053452,0.160356,0.024499,0.057906,0.026726,0.097996,0.004454,0.011136,0.133630
PRON,0.007833,0.015013,0.047650,0.077023,0.056136,0.000000,0.056136,0.056789,0.425587,0.135770,0.013055,0.005222,0.023499,0.001305,0.007833,0.071149
X,0.000805,0.030596,0.007246,0.006441,0.003221,0.006441,0.008052,0.006441,0.037037,0.432367,0.005636,0.000000,0.000000,0.406602,0.028180,0.020934
CCONJ,0.024553,0.026217,0.007074,0.257179,0.061590,0.001248,0.177695,0.027050,0.131086,0.033708,0.085726,0.005826,0.019975,0.011236,0.027882,0.101956
ADP,0.052520,0.046411,0.000000,0.459993,0.005875,0.000352,0.268124,0.001527,0.006110,0.011632,0.086829,0.000117,0.053930,0.005757,0.000117,0.000705

Алгоритм Витерби

In [16]:
def Viterbi(words, train_bag=train_tagged_words): # первый аргумент - список слов, которым нам нужно присвоить тег, второй - размеченная обучающая выборка
    state = []
    T = list(set([pair[1] for pair in train_bag])) # список всех возможных тегов

    for key, word in enumerate(notebook.tqdm(words)): # пронумеровываем список слов, чтобы можно было смотреть на предыдущее
        p = [] # инициализируем список столбцов вероятности для каждого наблюдения
        for tag in T: # считаем вероятность перехода
            if key == 0: # если предыдущего тега нет, то рассматриваем вероятность появления слова после знака препинания, в начале предложения
                transition_p = tags_df.loc['PUNCT', tag]
            else: # если предыдущий тег есть, то рассматриваем его
                transition_p = tags_df.loc[state[-1], tag]

            # вычисляем вероятности выбросов и состояний
            emission_p = word_given_tag(words[key], tag)[0]/word_given_tag(words[key], tag)[1] # вероятность выбросов ( насколько вероятно, что конкретное слово будет иметь конкретный тег)
            state_probability = emission_p * transition_p  # вероятность состояний (умножаем веротность того, что слово в принципе встречалось с этим тегом на вероятность перехода)
            p.append(state_probability)


        pmax = max(p) # выбираем максимальное значение из полученного списка
        # получаем наиболее вероятную последовательность скрытых состояний
        state_max = T[p.index(pmax)] # записываем его индекс и находим его соответствие в списке тегов
        state.append(state_max)
    return list(zip(words, state))

In [17]:
# протестируем алгоритм Витерби на нескольких примерах предложений тестового набора данных
random.seed(1234)      #определяем случайное значение

# выбираем случайные 10 значений
rndom = [random.randint(1,len(test_set)) for x in range(50)]

# список из 10 предложений, на которых мы тестируем модель
test_run = [test_set[i] for i in rndom]

# список размеченных слов
test_run_base = [tup for sent in test_run for tup in sent]

# список неразмеченных слов
test_tagged_words = [tup[0] for sent in test_run for tup in sent]

Проверяем скорость и точность алгоритма

In [18]:
start = time.time()
tagged_seq = Viterbi(test_tagged_words)
end = time.time() # считаем сколько времени это заняло
difference = end-start

print("Время в секундах: ", difference)

# проходим по парам (разметка_HMM, разметка_эталон) и если совпали, сохраняем в список
# по существу, нам просто нужно получить количество совпадений
check = [i for i, j in zip(tagged_seq, test_run_base) if i == j]

accuracy = len(check)/len(tagged_seq) # считаем точность
print('Точность алгоритма Витерби, %: ',accuracy*100)

  0%|          | 0/886 [00:00<?, ?it/s]

Время в секундах:  151.24469780921936
Точность алгоритма Витерби, %:  68.51015801354401

Ручная проверка

In [19]:
for our, reference in list(zip(tagged_seq, test_run_base))[:12]:
  print('Наша: {0:20}\tЭталон: {1:20}'.format(str(our), str(reference)))

Наша: ('Двери', 'DET')    	Эталон: ('Двери', 'NOUN')
Наша: ('из', 'ADP')       	Эталон: ('из', 'ADP')
Наша: ('вагонов', 'NOUN') 	Эталон: ('вагонов', 'NOUN')
Наша: ('поезда', 'NOUN')  	Эталон: ('поезда', 'NOUN')
Наша: ('не', 'PART')      	Эталон: ('не', 'PART')
Наша: ('открываются', 'DET')	Эталон: ('открываются', 'VERB')
Наша: ('.', 'PUNCT')      	Эталон: ('.', 'PUNCT')
Наша: ('Назвав', 'DET')   	Эталон: ('Назвав', 'VERB')
Наша: ('призванную', 'DET')	Эталон: ('призванную', 'VERB')
Наша: ('девушку', 'NOUN') 	Эталон: ('девушку', 'NOUN')
Наша: ('в', 'ADP')        	Эталон: ('в', 'ADP')
Наша: ('честь', 'NOUN')   	Эталон: ('честь', 'NOUN')

Автоматизированная проверка

In [51]:
# test_run_base =     [tup       for sent in test_run for tup in sent]
with_sent_numbers = [(i, *tup) for i, sent in enumerate(test_run) for tup in sent]
with_sent_numbers

[(0, 'Двери', 'NOUN'),
 (0, 'из', 'ADP'),
 (0, 'вагонов', 'NOUN'),
 (0, 'поезда', 'NOUN'),
 (0, 'не', 'PART'),
 (0, 'открываются', 'VERB'),
 (0, '.', 'PUNCT'),
 (1, 'Назвав', 'VERB'),
 (1, 'призванную', 'VERB'),
 (1, 'девушку', 'NOUN'),
 (1, 'в', 'ADP'),
 (1, 'честь', 'NOUN'),
 (1, 'своего', 'DET'),
 (1, 'кота', 'NOUN'),
 (1, '``', 'PUNCT'),
 (1, 'Танарот', 'PROPN'),
 (1, '&#39;&#39;', 'PUNCT'),
 (1, ',', 'PUNCT'),
 (1, 'он', 'PRON'),
 (1, 'тем', 'PRON'),
 (1, 'самым', 'ADJ'),
 (1, 'заключает', 'VERB'),
 (1, 'с', 'ADP'),
 (1, 'ней', 'PRON'),
 (1, 'контракт', 'NOUN'),
 (1, 'хозяина', 'NOUN'),
 (1, 'и', 'CCONJ'),
 (1, 'слуги', 'NOUN'),
 (1, '.', 'PUNCT'),
 (2, 'Председатель', 'NOUN'),
 (2, 'Социал-демократической', 'ADJ'),
 (2, 'партии', 'NOUN'),
 (2, 'Боснии', 'PROPN'),
 (2, 'и', 'CCONJ'),
 (2, 'Герцеговины', 'PROPN'),
 (2, '.', 'PUNCT'),
 (3, 'Телефонный', 'ADJ'),
 (3, 'код', 'NOUN'),
 (3, '--', 'PUNCT'),
 (3, '4739', 'NUM'),
 (3, '.', 'PUNCT'),
 (4, 'В', 'ADP'),
 (4, '1942', 'ADJ'),
 (4, 'году', 'NOUN'),
 (4, 'был', 'AUX'),
 (4, 'фактически', 'ADV'),
 (4, 'заключён', 'VERB'),
 (4, 'под', 'ADP'),
 (4, 'домашний', 'ADJ'),
 (4, 'арест', 'NOUN'),
 (4, '.', 'PUNCT'),
 (5, 'Начиная', 'VERB'),
 (5, 'с', 'ADP'),
 (5, 'сезона', 'NOUN'),
 (5, '2011/12', 'NUM'),
 (5, ',', 'PUNCT'),
 (5, 'подписал', 'VERB'),
 (5, 'двухгодовой', 'ADJ'),
 (5, 'контракт', 'NOUN'),
 (5, 'с', 'ADP'),
 (5, 'Байером', 'PROPN'),
 (5, ',', 'PUNCT'),
 (5, 'но', 'CCONJ'),
 (5, 'не', 'PART'),
 (5, 'доработал', 'VERB'),
 (5, 'до', 'ADP'),
 (5, 'конца', 'NOUN'),
 (5, 'этот', 'DET'),
 (5, 'срок', 'NOUN'),
 (5, ',', 'PUNCT'),
 (5, 'будучи', 'AUX'),
 (5, 'в', 'ADP'),
 (5, 'апреле', 'NOUN'),
 (5, '2012', 'ADJ'),
 (5, 'года', 'NOUN'),
 (5, 'сменённым', 'ADJ'),
 (5, 'на', 'ADP'),
 (5, 'тренерским', 'ADJ'),
 (5, 'посту', 'NOUN'),
 (5, 'финном', 'NOUN'),
 (5, 'Сами', 'PROPN'),
 (5, 'Хююпия', 'PROPN'),
 (5, '.', 'PUNCT'),
 (6, 'Черрилла', 'PROPN'),
 (6, 'и', 'CCONJ'),
 (6, 'его', 'DET'),
 (6, 'жены', 'NOUN'),
 (6, 'Бланш', 'PROPN'),
 (6, 'Уилкокс', 'PROPN'),
 (6, '.', 'PUNCT'),
 (7, 'Во', 'ADP'),
 (7, 'главе', 'NOUN'),
 (7, 'огромного', 'ADJ'),
 (7, 'войска', 'NOUN'),
 (7, 'хан', 'NOUN'),
 (7, 'через', 'ADP'),
 (7, 'Кураму', 'PROPN'),
 (7, 'подошел', 'VERB'),
 (7, 'к', 'ADP'),
 (7, 'берегу', 'NOUN'),
 (7, 'Чирчика', 'PROPN'),
 (7, 'и', 'CCONJ'),
 (7, 'устроил', 'VERB'),
 (7, 'здесь', 'ADV'),
 (7, 'охоту', 'NOUN'),
 (7, 'на', 'ADP'),
 (7, 'тигров', 'NOUN'),
 (7, ',', 'PUNCT'),
 (7, 'водившихся', 'VERB'),
 (7, 'в', 'ADP'),
 (7, 'изобилии', 'NOUN'),
 (7, '.', 'PUNCT'),
 (8, 'Решения', 'NOUN'),
 (8, 'иных', 'ADJ'),
 (8, 'органов', 'NOUN'),
 (8, 'по', 'ADP'),
 (8, 'гражданским', 'ADJ'),
 (8, 'делам', 'NOUN'),
 (8, 'также', 'PART'),
 (8, 'могут', 'VERB'),
 (8, 'быть', 'AUX'),
 (8, 'оспорены', 'VERB'),
 (8, 'в', 'ADP'),
 (8, 'суде', 'NOUN'),
 (8, '.', 'PUNCT'),
 (9, 'Персонажи', 'NOUN'),
 (9, 'этой', 'DET'),
 (9, 'сцены', 'NOUN'),
 (9, ',', 'PUNCT'),
 (9, 'помещённые', 'VERB'),
 (9, 'в', 'ADP'),
 (9, 'архитектурный', 'ADJ'),
 (9, 'антураж', 'NOUN'),
 (9, 'с', 'ADP'),
 (9, 'тонкими', 'ADJ'),
 (9, 'колоннами', 'NOUN'),
 (9, ',', 'PUNCT'),
 (9, 'выписаны', 'VERB'),
 (9, 'с', 'ADP'),
 (9, 'готическим', 'ADJ'),
 (9, 'изяществом', 'NOUN'),
 (9, ',', 'PUNCT'),
 (9, 'им', 'PRON'),
 (9, 'присуща', 'ADJ'),
 (9, 'живая', 'ADJ'),
 (9, 'жестикуляция', 'NOUN'),
 (9, '.', 'PUNCT'),
 (10, 'Обучение', 'NOUN'),
 (10, 'танкистов', 'NOUN'),
 (10, 'по', 'ADP'),
 (10, 'немецким', 'ADJ'),
 (10, 'канонам', 'NOUN'),
 (10, 'было', 'AUX'),
 (10, 'завершено', 'VERB'),
 (10, '.', 'PUNCT'),
 (11, 'Среди', 'ADP'),
 (11, 'его', 'DET'),
 (11, 'учителей', 'NOUN'),
 (11, 'были', 'VERB'),
 (11, 'историк', 'NOUN'),
 (11, 'Ян', 'PROPN'),
 (11, 'Длугош', 'PROPN'),
 (11, 'и', 'CCONJ'),
 (11, 'поэт', 'NOUN'),
 (11, 'Каллимах', 'PROPN'),
 (11, '(', 'PUNCT'),
 (11, 'в', 'ADP'),
 (11, '1472', 'ADJ'),
 (11, '--', 'PUNCT'),
 (11, '1474', 'ADJ'),
 (11, 'годах', 'NOUN'),
 (11, ')', 'PUNCT'),
 (11, ',', 'PUNCT'),
 (11, 'а', 'CCONJ'),
 (11, 'также', 'CCONJ'),
 (11, 'Станислав', 'PROPN'),
 (11, 'Шидловецкий', 'PROPN'),
 (11, '.', 'PUNCT'),
 (12, 'Во', 'ADP'),
 (12, 'время', 'NOUN'),
 (12, 'лечения', 'NOUN'),
 (12, 'следует', 'VERB'),
 (12, 'воздерживаться', 'VERB'),
 (12, 'от', 'ADP'),
 (12, 'приёма', 'NOUN'),
 (12, 'алкоголя', 'NOUN'),
 (12, 'и', 'CCONJ'),
 (12, 'занятий', 'NOUN'),
 (12, 'потенциально', 'ADV'),
 (12, 'опасными', 'ADJ'),
 (12, 'видами', 'NOUN'),
 (12, 'деятельности', 'NOUN'),
 (12, ',', 'PUNCT'),
 (12, 'требующими', 'VERB'),
 (12, 'повышенного', 'ADJ'),
 (12, 'внимания', 'NOUN'),
 (12, 'и', 'CCONJ'),
 (12, 'быстроты', 'NOUN'),
 (12, 'психических', 'ADJ'),
 (12, 'и', 'CCONJ'),
 (12, 'двигательных', 'ADJ'),
 (12, 'реакций', 'NOUN'),
 (12, '.', 'PUNCT'),
 (13, 'В', 'ADP'),
 (13, '1920', 'ADJ'),
 (13, '-', 'PUNCT'),
 (13, '1940-х', 'ADJ'),
 (13, 'Сноу', 'PROPN'),
 (13, 'опубликовал', 'VERB'),
 (13, 'пять', 'NUM'),
 (13, 'своих', 'DET'),
 (13, 'книг', 'NOUN'),
 (13, 'в', 'ADP'),
 (13, 'журнале', 'NOUN'),
 (13, 'мистики', 'NOUN'),
 (13, 'и', 'CCONJ'),
 (13, 'саспенса', 'NOUN'),
 (13, 'Weird', 'X'),
 (13, 'Tales', 'X'),
 (13, ':', 'PUNCT'),
 (13, '``', 'PUNCT'),
 (13, 'Ночные', 'ADJ'),
 (13, 'Крылья', 'NOUN'),
 (13, '&#39;&#39;', 'PUNCT'),
 (13, '(', 'PUNCT'),
 (13, '1927', 'ADJ'),
 (13, ')', 'PUNCT'),
 (13, ',', 'PUNCT'),
 (13, '``', 'PUNCT'),
 (13, 'Яд', 'NOUN'),
 (13, '&#39;&#39;', 'PUNCT'),
 (13, '(', 'PUNCT'),
 (13, '1928', 'ADJ'),
 (13, ')', 'PUNCT'),
 (13, ',', 'PUNCT'),
 (13, '``', 'PUNCT'),
 (13, 'Второе', 'ADJ'),
 (13, 'детство', 'NOUN'),
 (13, '&#39;&#39;', 'PUNCT'),
 (13, '(', 'PUNCT'),
 (13, '1945', 'ADJ'),
 (13, ')', 'PUNCT'),
 (13, ',', 'PUNCT'),
 (13, '``', 'PUNCT'),
 (13, 'Семя', 'NOUN'),
 (13, '&#39;&#39;', 'PUNCT'),
 (13, '(', 'PUNCT'),
 (13, '1946', 'ADJ'),
 (13, ')', 'PUNCT'),
 (13, 'и', 'CCONJ'),
 (13, '``', 'PUNCT'),
 (13, 'Полночь', 'NOUN'),
 (13, '&#39;&#39;', 'PUNCT'),
 (13, '(', 'PUNCT'),
 (13, '1946', 'ADJ'),
 (13, ')', 'PUNCT'),
 (13, '.', 'PUNCT'),
 (14, 'В', 'ADP'),
 (14, '1822', 'ADJ'),
 (14, 'году', 'NOUN'),
 (14, 'англичане', 'NOUN'),
 (14, 'сделали', 'VERB'),
 (14, 'шаг', 'NOUN'),
 (14, 'навстречу', 'ADP'),
 (14, 'производителям', 'NOUN'),
 (14, ',', 'PUNCT'),
 (14, 'узаконив', 'VERB'),
 (14, 'многие', 'ADJ'),
 (14, 'новые', 'ADJ'),
 (14, 'винокурни', 'NOUN'),
 (14, 'и', 'CCONJ'),
 (14, 'снизив', 'VERB'),
 (14, 'налоги', 'NOUN'),
 (14, 'на', 'ADP'),
 (14, 'производство', 'NOUN'),
 (14, '.', 'PUNCT'),
 (15, 'Журнал', 'NOUN'),
 (15, 'управляется', 'VERB'),
 (15, 'некоммерческой', 'ADJ'),
 (15, 'образовательной', 'ADJ'),
 (15, 'организацией', 'NOUN'),
 (15, 'Annals', 'X'),
 (15, 'of', 'X'),
 (15, 'Botany', 'X'),
 (15, 'Company', 'X'),
 (15, 'и', 'CCONJ'),
 (15, 'публикуется', 'VERB'),
 (15, 'университетским', 'ADJ'),
 (15, 'издательством', 'NOUN'),
 (15, 'Oxford', 'X'),
 (15, 'University', 'X'),
 (15, 'Press', 'X'),
 (15, ';', 'PUNCT'),
 (15, 'его', 'DET'),
 (15, 'импакт-фактор', 'NOUN'),
 (15, 'согласно', 'ADP'),
 (15, 'ISI', 'PROPN'),
 (15, 'в', 'ADP'),
 (15, '2008', 'ADJ'),
 (15, 'году', 'NOUN'),
 (15, 'равнялся', 'VERB'),
 (15, '2,755', 'NUM'),
 (15, '.', 'PUNCT'),
 (16, 'Телефонный', 'ADJ'),
 (16, 'код', 'NOUN'),
 (16, '--', 'PUNCT'),
 (16, '3238', 'NUM'),
 (16, '.', 'PUNCT'),
 (17, 'После', 'ADP'),
 (17, 'сезона', 'NOUN'),
 (17, '2003/04', 'NUM'),
 (17, 'выступал', 'VERB'),
 (17, 'за', 'ADP'),
 (17, '``', 'PUNCT'),
 (17, 'Леон', 'PROPN'),
 (17, '&#39;&#39;', 'PUNCT'),
 (17, 'и', 'CCONJ'),
 (17, '``', 'PUNCT'),
 (17, 'Коацакоалькос', 'PROPN'),
 (17, '&#39;&#39;', 'PUNCT'),
 (17, '.', 'PUNCT'),
 (18, 'В', 'ADP'),
 (18, 'результате', 'NOUN'),
 (18, '15', 'ADJ'),
 (18, 'сентября', 'NOUN'),
 (18, 'отряд', 'NOUN'),
 (18, 'покинула', 'VERB'),
 (18, 'часть', 'NOUN'),
 (18, 'офицеров', 'NOUN'),
 (18, '(', 'PUNCT'),
 (18, 'включая', 'ADP'),
 (18, 'штабс-капитана', 'NOUN'),
 (18, 'Александра', 'PROPN'),
 (18, 'Пунина', 'PROPN'),
 (18, 'и', 'CCONJ'),
 (18, 'штабс-капитана', 'NOUN'),
 (18, 'Льва', 'PROPN'),
 (18, 'Пунина', 'PROPN'),
 (18, ')', 'PUNCT'),
 (18, 'и', 'CCONJ'),
 (18, 'нижние', 'ADJ'),
 (18, 'чины', 'NOUN'),
 (18, '(', 'PUNCT'),
 (18, '3-й', 'ADJ'),
 (18, 'эскадрон', 'NOUN'),
 (18, 'полностью', 'ADV'),
 (18, 'и', 'CCONJ'),
 (18, '1', 'ADJ'),
 (18, 'и', 'CCONJ'),
 (18, '2', 'ADJ'),
 (18, 'частично', 'ADV'),
 (18, ')', 'PUNCT'),
 (18, '.', 'PUNCT'),
 (19, 'За', 'ADP'),
 (19, 'головкой', 'NOUN'),
 (19, 'самонаведения', 'NOUN'),
 (19, 'находится', 'VERB'),
 (19, 'осколочно-фугасная', 'ADJ'),
 (19, 'боевая', 'ADJ'),
 (19, 'часть', 'NOUN'),
 (19, 'общей', 'ADJ'),
 (19, 'массой', 'NOUN'),
 (19, '70', 'NUM'),
 (19, 'кг', 'NOUN'),
 (19, '.', 'PUNCT'),
 (20, 'Южнее', 'ADP'),
 (20, 'станции', 'NOUN'),
 (20, ',', 'PUNCT'),
 (20, 'от', 'ADP'),
 (20, 'локальных', 'ADJ'),
 (20, 'путей', 'NOUN'),
 (20, ',', 'PUNCT'),
 (20, 'отходили', 'VERB'),
 (20, 'соединительные', 'ADJ'),
 (20, 'пути', 'NOUN'),
 (20, 'к', 'ADP'),
 (20, 'ныне', 'ADV'),
 (20, 'уже', 'ADV'),
 (20, 'не', 'PART'),
 (20, 'существующей', 'VERB'),
 (20, 'линии', 'NOUN'),
 (20, ',', 'PUNCT'),
 (20, 'и', 'CCONJ'),
 (20, 'в', 'ADP'),
 (20, 'период', 'NOUN'),
 (20, 'с', 'ADP'),
 (20, '1940', 'ADJ'),
 (20, 'по', 'ADP'),
 (20, '1958', 'ADJ'),
 (20, 'годы', 'NOUN'),
 (20, ',', 'PUNCT'),
 (20, 'станция', 'NOUN'),
 (20, 'была', 'AUX'),
 (20, 'конечной', 'ADJ'),
 (20, 'точкой', 'NOUN'),
 (20, 'для', 'ADP'),
 (20, 'поездов', 'NOUN'),
 (20, 'этой', 'DET'),
 (20, 'линии', 'NOUN'),
 (20, '.', 'PUNCT'),
 (21, 'Однако', 'CCONJ'),
 (21, 'Дорошенко', 'PROPN'),
 (21, 'недостаточно', 'ADV'),
 (21, 'хорошо', 'ADV'),
 (21, 'справлялся', 'VERB'),
 (21, 'со', 'ADP'),
 (21, 'своими', 'DET'),
 (21, 'обязанностями', 'NOUN'),
 (21, '.', 'PUNCT'),
 (22, 'Зофья', 'PROPN'),
 (22, 'Лисса', 'PROPN'),
 (22, '--', 'PUNCT'),
 (22, 'автор', 'NOUN'),
 (22, 'около', 'ADP'),
 (22, '600', 'NUM'),
 (22, 'научных', 'ADJ'),
 (22, 'работ', 'NOUN'),
 (22, ',', 'PUNCT'),
 (22, 'включая', 'VERB'),
 (22, 'более', 'ADV'),
 (22, 'десятка', 'NOUN'),
 (22, 'книг', 'NOUN'),
 (22, ',', 'PUNCT'),
 (22, 'сотни', 'NOUN'),
 (22, 'выступлений', 'NOUN'),
 (22, 'и', 'CCONJ'),
 (22, 'статей', 'NOUN'),
 (22, ',', 'PUNCT'),
 (22, 'многие', 'ADJ'),
 (22, 'из', 'ADP'),
 (22, 'которых', 'PRON'),
 (22, 'были', 'AUX'),
 (22, 'переведены', 'VERB'),
 (22, 'на', 'ADP'),
 (22, 'иностранные', 'ADJ'),
 (22, 'языки', 'NOUN'),
 (22, '.', 'PUNCT'),
 (23, 'От', 'ADP'),
 (23, 'Рака', 'PROPN'),
 (23, 'ведут', 'VERB'),
 (23, 'род', 'NOUN'),
 (23, 'Гинтовты', 'PROPN'),
 (23, '-', 'PUNCT'),
 (23, 'Дзевалтовские', 'PROPN'),
 (23, '.', 'PUNCT'),
 (24, 'Они', 'PRON'),
 (24, 'узнают', 'VERB'),
 (24, ',', 'PUNCT'),
 (24, 'что', 'SCONJ'),
 (24, 'Джарт', 'PROPN'),
 (24, 'превратил', 'VERB'),
 (24, 'себя', 'PRON'),
 (24, 'в', 'ADP'),
 (24, 'Живую', 'ADJ'),
 (24, 'Карту', 'NOUN'),
 (24, '(', 'PUNCT'),
 (24, 'по', 'ADP'),
 (24, ',', 'PUNCT'),
 (24, 'крайней', 'ADJ'),
 (24, 'мере', 'NOUN'),
 (24, 'частично', 'ADV'),
 (24, ')', 'PUNCT'),
 (24, ',', 'PUNCT'),
 (24, 'как', 'ADV'),
 (24, 'это', 'PRON'),
 (24, 'уже', 'ADV'),
 (24, 'сделал', 'VERB'),
 (24, 'Брэнд', 'PROPN'),
 (24, ',', 'PUNCT'),
 (24, 'а', 'CCONJ'),
 (24, 'Маской', 'NOUN'),
 (24, 'оказывается', 'VERB'),
 (24, 'бывшая', 'ADJ'),
 (24, 'подруга', 'NOUN'),
 (24, 'Мерлина', 'PROPN'),
 (24, 'Джулия', 'PROPN'),
 (24, '.', 'PUNCT'),
 (25, 'Петр', 'PROPN'),
 (25, 'Мамонов', 'PROPN'),
 (25, 'предлагает', 'VERB'),
 (25, 'музыкантам', 'NOUN'),
 (25, 'группы', 'NOUN'),
 (25, 'записать', 'VERB'),
 (25, 'совместный', 'ADJ'),
 (25, 'альбом', 'NOUN'),
 (25, '(', 'PUNCT'),
 (25, 'чему', 'PRON'),
 (25, 'помешал', 'VERB'),
 (25, 'отъезд', 'NOUN'),
 (25, 'гранда', 'NOUN'),
 (25, 'на', 'ADP'),
 (25, 'ПМЖ', 'NOUN'),
 (25, 'в', 'ADP'),
 (25, 'деревню', 'NOUN'),
 (25, ')', 'PUNCT'),
 (25, '.', 'PUNCT'),
 (26, 'Фюзеляж', 'NOUN'),
 (26, 'самолёта', 'NOUN'),
 (26, 'деревянный', 'ADJ'),
 (26, ',', 'PUNCT'),
 (26, 'типа', 'ADP'),
 (26, 'монокок', 'NOUN'),
 (26, ',', 'PUNCT'),
 (26, 'овального', 'ADJ'),
 (26, 'сечения', 'NOUN'),
 (26, ',', 'PUNCT'),
 (26, 'переходящий', 'VERB'),
 (26, 'в', 'ADP'),
 (26, 'хвостовой', 'ADJ'),
 (26, 'части', 'NOUN'),
 (26, 'в', 'ADP'),
 (26, 'килевую', 'ADJ'),
 (26, 'ферму', 'NOUN'),
 (26, '.', 'PUNCT'),
 (27, 'По', 'ADP'),
 (27, 'итогам', 'NOUN'),
 (27, 'сезона', 'NOUN'),
 (27, 'два', 'NUM'),
 (27, 'клуба', 'NOUN'),
 (27, ',', 'PUNCT'),
 (27, 'занявшие', 'VERB'),
 (27, 'последние', 'ADJ'),
 (27, 'места', 'NOUN'),
 (27, ',', 'PUNCT'),
 (27, 'понижаются', 'VERB'),
 (27, 'в', 'ADP'),
 (27, 'классе', 'NOUN'),
 (27, ',', 'PUNCT'),
 (27, 'а', 'CCONJ'),
 (27, 'третий', 'ADJ'),
 (27, 'клуб', 'NOUN'),
 (27, 'с', 'ADP'),
 (27, 'конца', 'NOUN'),
 (27, 'играет', 'VERB'),
 (27, 'переходные', 'ADJ'),
 (27, 'матчи', 'NOUN'),
 (27, '.', 'PUNCT'),
 (28, 'По', 'ADP'),
 (28, 'некоторым', 'DET'),
 (28, 'данным', 'NOUN'),
 (28, ',', 'PUNCT'),
 (28, 'участвовал', 'VERB'),
 (28, 'в', 'ADP'),
 (28, 'боях', 'NOUN'),
 (28, 'на', 'ADP'),
 (28, 'озере', 'NOUN'),
 (28, 'Хасан', 'PROPN'),
 (28, ',', 'PUNCT'),
 (28, 'был', 'AUX'),
 (28, 'ранен', 'VERB'),
 (28, '.', 'PUNCT'),
 (29, 'Однако', 'CCONJ'),
 (29, ',', 'PUNCT'),
 (29, 'согласно', 'ADP'),
 (29, 'оценке', 'NOUN'),
 (29, 'Европейской', 'ADJ'),
 (29, 'комиссии', 'NOUN'),
 (29, 'это', 'PRON'),
 (29, 'все', 'ADV'),
 (29, 'еще', 'ADV'),
 (29, 'ниже', 'ADJ'),
 (29, 'уровня', 'NOUN'),
 (29, 'наилучших', 'ADJ'),
 (29, 'существующих', 'VERB'),
 (29, 'технологий', 'NOUN'),
 (29, '(', 'PUNCT'),
 (29, 'НСТ', 'PROPN'),
 (29, ')', 'PUNCT'),
 (29, ',', 'PUNCT'),
 (29, 'которые', 'PRON'),
 (29, 'имеют', 'VERB'),
 (29, 'эффективность', 'NOUN'),
 (29, '46-49', 'NUM'),
 (29, '%', 'SYM'),
 (29, '.', 'PUNCT'),
 (30, 'В', 'ADP'),
 (30, 'письме', 'NOUN'),
 (30, ',', 'PUNCT'),
 (30, 'одно', 'NUM'),
 (30, 'из', 'ADP'),
 (30, 'племен', 'NOUN'),
 (30, 'принадлежит', 'VERB'),
 (30, 'Коннору', 'PROPN'),
 (30, '.', 'PUNCT'),
 (31, '28', 'ADJ'),
 (31, 'сентября', 'NOUN'),
 (31, ':', 'PUNCT'),
 (31, 'Казахстан', 'PROPN'),
 (31, '--', 'PUNCT'),
 (31, 'Южная', 'ADJ'),
 (31, 'Корея', 'PROPN'),
 (31, '3:1', 'NUM'),
 (31, '(', 'PUNCT'),
 (31, '21:25', 'NUM'),
 (31, ',', 'PUNCT'),
 (31, '25:22', 'NUM'),
 (31, ',', 'PUNCT'),
 (31, '25:17', 'NUM'),
 (31, ',', 'PUNCT'),
 (31, '25:14', 'NUM'),
 (31, ')', 'PUNCT'),
 (31, ';', 'PUNCT'),
 (31, 'Китай', 'PROPN'),
 (31, '--', 'PUNCT'),
 (31, 'Новая', 'ADJ'),
 (31, 'Зеландия', 'PROPN'),
 (31, '3:0', 'NUM'),
 (31, '(', 'PUNCT'),
 (31, '25:4', 'NUM'),
 (31, ',', 'PUNCT'),
 (31, '25:7', 'NUM'),
 (31, ',', 'PUNCT'),
 (31, '25:7', 'NUM'),
 (31, ')', 'PUNCT'),
 (31, '.', 'PUNCT'),
 (32, 'После', 'ADP'),
 (32, 'окончания', 'NOUN'),
 (32, 'войны', 'NOUN'),
 (32, 'Степанов', 'PROPN'),
 (32, 'активно', 'ADV'),
 (32, 'сотрудничал', 'VERB'),
 (32, 'с', 'ADP'),
 (32, 'православными', 'ADJ'),
 (32, 'и', 'CCONJ'),
 (32, 'монархическими', 'ADJ'),
 (32, 'изданиями', 'NOUN'),
 (32, 'русской', 'ADJ'),
 (32, 'эмиграции', 'NOUN'),
 (32, '.', 'PUNCT'),
 (33, 'Сила', 'NOUN'),
 (33, 'трения', 'NOUN'),
 (33, 'незначительная', 'ADJ'),
 (33, '.', 'PUNCT'),
 (34, 'У', 'ADP'),
 (34, 'пациентов', 'NOUN'),
 (34, ',', 'PUNCT'),
 (34, 'принимающих', 'VERB'),
 (34, 'темазепам', 'NOUN'),
 (34, 'более', 'ADV'),
 (34, '2-3', 'NUM'),
 (34, 'нед', 'NOUN'),
 (34, ',', 'PUNCT'),
 (34, 'необходима', 'ADJ'),
 (34, 'периодическая', 'ADJ'),
 (34, 'переоценка', 'NOUN'),
 (34, 'эффективности', 'NOUN'),
 (34, 'для', 'ADP'),
 (34, 'определения', 'NOUN'),
 (34, 'целесообразности', 'NOUN'),
 (34, 'его', 'DET'),
 (34, 'дальнейшего', 'ADJ'),
 (34, 'использования', 'NOUN'),
 (34, '.', 'PUNCT'),
 (35, 'Всего', 'ADV'),
 (35, 'выпущено', 'VERB'),
 (35, 'было', 'AUX'),
 (35, 'менее', 'ADV'),
 (35, '1000', 'NUM'),
 (35, 'экземпляров', 'NOUN'),
 (35, '.', 'PUNCT'),
 (36, 'Писал', 'VERB'),
 (36, 'портреты', 'NOUN'),
 (36, 'поразительного', 'ADJ'),
 (36, 'сходства', 'NOUN'),
 (36, 'с', 'ADP'),
 (36, 'немецких', 'ADJ'),
 (36, 'и', 'CCONJ'),
 (36, 'французских', 'ADJ'),
 (36, 'государей', 'NOUN'),
 (36, 'своей', 'DET'),
 (36, 'эпохи', 'NOUN'),
 (36, '.', 'PUNCT'),
 (37, 'Он', 'PRON'),
 (37, 'отстреливает', 'VERB'),
 (37, 'вампиров', 'NOUN'),
 (37, ',', 'PUNCT'),
 (37, 'ему', 'PRON'),
 (37, 'помогают', 'VERB'),
 (37, 'две', 'NUM'),
 (37, 'автоматические', 'ADJ'),
 (37, 'турели', 'NOUN'),
 (37, '.', 'PUNCT'),
 (38, 'Жандармы', 'NOUN'),
 (38, 'всерьёз', 'ADV'),
 (38, 'начинают', 'VERB'),
 (38, 'беспокоиться', 'VERB'),
 (38, 'о', 'ADP'),
 (38, 'состоянии', 'NOUN'),
 (38, 'здоровья', 'NOUN'),
 (38, 'своего', 'DET'),
 (38, 'коллеги', 'NOUN'),
 (38, '.', 'PUNCT'),
 (39, 'Уголовный', 'ADJ'),
 (39, 'кодекс', 'NOUN'),
 (39, 'Российской', 'ADJ'),
 (39, 'Федерации', 'NOUN'),
 (39, '(', 'PUNCT'),
 (39, 'УК', 'NOUN'),
 (39, 'РФ', 'PROPN'),
 (39, ')', 'PUNCT'),
 (39, '--', 'PUNCT'),
 (39, 'основной', 'ADJ'),
 (39, 'и', 'CCONJ'),
 (39, 'единственный', 'ADJ'),
 (39, 'источник', 'NOUN'),
 (39, 'уголовного', 'ADJ'),
 (39, 'права', 'NOUN'),
 (39, ',', 'PUNCT'),
 (39, 'единственный', 'ADJ'),
 (39, 'нормативный', 'ADJ'),
 (39, 'акт', 'NOUN'),
 (39, ',', 'PUNCT'),
 (39, 'устанавливающий', 'VERB'),
 (39, 'преступность', 'NOUN'),
 (39, 'и', 'CCONJ'),
 (39, 'наказуемость', 'NOUN'),
 (39, 'деяний', 'NOUN'),
 (39, 'на', 'ADP'),
 (39, 'территории', 'NOUN'),
 (39, 'Российской', 'ADJ'),
 (39, 'Федерации', 'NOUN'),
 (39, ',', 'PUNCT'),
 (39, 'России', 'PROPN'),
 (39, '.', 'PUNCT'),
 (40, 'Артёма', 'PROPN'),
 (40, 'и', 'CCONJ'),
 (40, 'Михаила', 'PROPN'),
 (40, 'охрана', 'NOUN'),
 (40, 'пропускает', 'VERB'),
 (40, ',', 'PUNCT'),
 (40, 'а', 'CCONJ'),
 (40, 'Ванечку', 'PROPN'),
 (40, 'убивает', 'VERB'),
 (40, 'офицер', 'NOUN'),
 (40, '.', 'PUNCT'),
 (41, 'Наибольшие', 'ADJ'),
 (41, 'глубины', 'NOUN'),
 (41, 'расположены', 'VERB'),
 (41, 'в', 'ADP'),
 (41, 'центре', 'NOUN'),
 (41, 'озера', 'NOUN'),
 (41, ',', 'PUNCT'),
 (41, 'средняя', 'ADJ'),
 (41, 'глубина', 'NOUN'),
 (41, '--', 'PUNCT'),
 (41, '5,4', 'NUM'),
 (41, 'м', 'NOUN'),
 (41, '.', 'PUNCT'),
 (42, 'Ещё', 'ADV'),
 (42, 'несколько', 'NUM'),
 (42, 'премий', 'NOUN'),
 (42, ',', 'PUNCT'),
 (42, 'увековечивших', 'VERB'),
 (42, 'его', 'DET'),
 (42, 'карьеру', 'NOUN'),
 (42, 'художника', 'NOUN'),
 (42, ',', 'PUNCT'),
 (42, 'среди', 'ADP'),
 (42, 'которых', 'PRON'),
 (42, 'Гран-При', 'NOUN'),
 (42, 'Генерального', 'ADJ'),
 (42, 'консула', 'NOUN'),
 (42, 'Сейны', 'PROPN'),
 (42, 'и', 'CCONJ'),
 (42, 'Марны', 'PROPN'),
 (42, '(', 'PUNCT'),
 (42, 'Seine', 'X'),
 (42, '-', 'PUNCT'),
 (42, 'et', 'X'),
 (42, '-', 'PUNCT'),
 (42, 'Marne', 'X'),
 (42, ')', 'PUNCT'),
 (42, 'в', 'ADP'),
 (42, '1974', 'ADJ'),
 (42, '.', 'PUNCT'),
 (43, 'Келер', 'PROPN'),
 (43, 'приказал', 'VERB'),
 (43, 'комиту', 'NOUN'),
 (43, 'Юстину', 'PROPN'),
 (43, 'собрать', 'VERB'),
 (43, 'войска', 'NOUN'),
 (43, ',', 'PUNCT'),
 (43, 'но', 'CCONJ'),
 (43, 'тому', 'DET'),
 (43, 'не', 'PART'),
 (43, 'удалось', 'VERB'),
 (43, 'заставить', 'VERB'),
 (43, 'разошедшихся', 'VERB'),
 (43, 'солдат', 'NOUN'),
 (43, 'вернуться', 'VERB'),
 (43, '.', 'PUNCT'),
 (44, 'Играет', 'VERB'),
 (44, 'во', 'ADP'),
 (44, 'Второй', 'ADJ'),
 (44, 'лиге', 'NOUN'),
 (44, 'группы', 'NOUN'),
 (44, 'А', 'NOUN'),
 (44, '.', 'PUNCT'),
 (45, 'Говоры', 'NOUN'),
 (45, 'отделов', 'NOUN'),
 (45, 'Б', 'NOUN'),
 (45, 'и', 'CCONJ'),
 (45, 'В', 'PROPN'),
 (45, ',', 'PUNCT'),
 (45, 'вероятно', 'ADV'),
 (45, ',', 'PUNCT'),
 (45, 'генетически', 'ADV'),
 (45, 'являлись', 'VERB'),
 (45, 'частью', 'NOUN'),
 (45, 'говоров', 'NOUN'),
 (45, 'Рязанской', 'ADJ'),
 (45, 'группы', 'NOUN'),
 (45, ',', 'PUNCT'),
 (45, 'испытавших', 'VERB'),
 (45, 'сильное', 'ADJ'),
 (45, 'влияние', 'NOUN'),
 (45, 'московских', 'ADJ'),
 (45, 'и', 'CCONJ'),
 (45, 'владимирских', 'ADJ'),
 (45, 'говоров', 'NOUN'),
 (45, '.', 'PUNCT'),
 (46, 'Пакет', 'NOUN'),
 (46, 'из', 'ADP'),
 (46, 'металлизированного', 'ADJ'),
 (46, 'полиэтилена', 'NOUN'),
 (46, 'с', 'ADP'),
 (46, 'нанесённой', 'VERB'),
 (46, 'инструкцией', 'NOUN'),
 (46, '.', 'PUNCT'),
 (47, 'Творчество', 'NOUN'),
 (47, 'Мирзы', 'PROPN'),
 (47, 'Кадыма', 'PROPN'),
 (47, 'Эривани', 'PROPN'),
 (47, 'свидетельствует', 'VERB'),

In [38]:
kwiks = []
for sent_i, tk, pos in with_sent_numbers:
    current_sentence = [tk for sent_j, tk, pos in with_sent_numbers if sent_j==sent_i]
    tk_index_in_sent = current_sentence.index(tk)
    kwik = current_sentence[max(0, tk_index_in_sent-3):min(len(sent)+1, tk_index_in_sent+4)]
    kwiks.append((tk, pos, ' '.join(current_sentence), ' '.join(kwik)))

In [ ]:
mismatches = []
for our, reference in zip (tagged_seq, kwiks):
    # print(our, reference)
    if our[1] != reference[1]:
        mismatches.append((our[0], our[1], *reference[1:]))  
mismatches_df = pd.DataFrame(mismatches, columns=['Слово', 'Наша разметка', 'Эталонная разметка', 'SENT_CONTEXT', '3_WIK'])
mismatches_df.index = range(1, len(mismatches_df) + 1)
mismatches_df.to_excel('Mismatches.xlsx', index=False)
display(mismatches_df)

,Слово,Наша разметка,Эталонная разметка,SENT_CONTEXT,3_WIK
1,Двери,DET,NOUN,Двери из вагонов поезда не открываются .,Двери из вагонов поезда
2,открываются,DET,VERB,Двери из вагонов поезда не открываются .,вагонов поезда не открываются .
3,Назвав,DET,VERB,Назвав призванную девушку в честь своего кота ...,Назвав призванную девушку в
4,призванную,DET,VERB,Назвав призванную девушку в честь своего кота ...,Назвав призванную девушку в честь
5,кота,DET,NOUN,Назвав призванную девушку в честь своего кота ...,в честь своего кота `` Танарот &#39;&#39;
...,...,...,...,...,...
275,и,PART,CCONJ,Окисляется на воздухе или по действием иода до...,"иода до азотистой и азотной кислот ,"
276,азотной,DET,ADJ,Окисляется на воздухе или по действием иода до...,"до азотистой и азотной кислот , под"
277,кислот,DET,NOUN,Окисляется на воздухе или по действием иода до...,"азотистой и азотной кислот , под действием"
278,перманганата,DET,NOUN,Окисляется на воздухе или по действием иода до...,", под действием перманганата -- до азотной"
279,азотной,DET,ADJ,Окисляется на воздухе или по действием иода до...,"до азотистой и азотной кислот , под"

In [52]:
mismatches_df[['Наша разметка', 'Эталонная разметка']].value_counts()

Наша разметка  Эталонная разметка
DET            NOUN                  90
               PROPN                 48
               ADJ                   47
               VERB                  42
PART           CCONJ                 15
DET            NUM                   14
               X                      7
NUM            ADJ                    3
DET            ADV                    2
PRON           DET                    1
DET            SYM                    1
ADJ            NUM                    1
ADP            ADV                    1
DET            ADP                    1
CCONJ          NOUN                   1
AUX            VERB                   1
ADV            ADP                    1
               ADJ                    1
ADP            PROPN                  1
VERB           ADP                    1
Name: count, dtype: int64

In [45]:
mismatches = []
for our, reference in zip (tagged_seq, test_run_base):
    if our != reference:  
        mismatches.append((our[0], our[1], reference[1]))  
mismatches_df = pd.DataFrame(mismatches, columns=['Слово', 'Наша разметка', 'Эталонная разметка'])
mismatches_df.index = range(1, len(mismatches_df) + 1)
mismatches_df.to_excel('Mismatches.xlsx', index=False)
display (mismatches_df)

            Слово Наша разметка Эталонная разметка
1           Двери           DET               NOUN
2     открываются           DET               VERB
3          Назвав           DET               VERB
4      призванную           DET               VERB
5            кота           DET               NOUN
..            ...           ...                ...
275             и          PART              CCONJ
276       азотной           DET                ADJ
277        кислот           DET               NOUN
278  перманганата           DET               NOUN
279       азотной           DET                ADJ

[279 rows x 3 columns]